In [1]:
import numpy as np

BASIC 

In [2]:
np.array([1,2,3])

array([1, 2, 3])

In [3]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
a= np.array([[2,4,5,6,],[8,6,4,7]])
print(a)

[[2 4 5 6]
 [8 6 4 7]]


In [5]:
print(a.dtype)
a.shape
a.ndim
a.reshape(4,2)

int32


array([[2, 4],
       [5, 6],
       [8, 6],
       [4, 7]])

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [8]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.random.random((2,3))

array([[0.12861251, 0.89168045, 0.77212133],
       [0.98002471, 0.33091792, 0.77590351]])

In [11]:
b= np.array([[2,4,6,7],[1,4,6,8],[2,3,5,9]])
print(b)

[[2 4 6 7]
 [1 4 6 8]
 [2 3 5 9]]


In [12]:
b[2,1:3]

array([3, 5])

In [13]:
b[2,1:3] = [7,10]
print(b)

[[ 2  4  6  7]
 [ 1  4  6  8]
 [ 2  7 10  9]]


In [14]:
np.full((3,4),9)
d = np.full((3,4),9)